### ISSUE TITLE
regrtest failure with multiprocessing

### ISSUE THREAD

**Issue by nirs** [nirs/cthreading#3]
Reproduce:
$ python regrtest.py

Result:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 506, in _terminate_pool
    worker_handler.join(1e100)
  File "/usr/lib64/python2.7/threading.py", line 963, in join
    self.__block.wait(delay, balancing)
OverflowError: timeout value is too large
```

Expected:
Python regrtest should pass

Check if (and how) multiprocessing tests pass without cthreading. cthreading should accept larger timeouts compared with Python 2.7.

Looks like wrong test, maybe need python patch?

**Comment by nirs** [comment]
Fixed in 41dd595
