### ISSUE TITLE
Some Python regression tests expect threading.ThreadError instead of RuntimeError

### ISSUE THREAD

**Issue by nirs** [nirs/cthreading#4]
# 
## ERROR: test_lock (test.test_multiprocessing.WithThreadsTestLock)

Traceback (most recent call last):
  File "/usr/lib64/python2.7/test/test_multiprocessing.py", line 654, in test_lock
    self.assertRaises((ValueError, threading.ThreadError), lock.release)
  File "/usr/lib64/python2.7/unittest/case.py", line 513, in assertRaises
    callableObj(_args, *_kwargs)
RuntimeError: release unlocked lock
# 
## ERROR: test_lock (test.test_multiprocessing.WithManagerTestLock)

Traceback (most recent call last):
  File "/usr/lib64/python2.7/test/test_multiprocessing.py", line 654, in test_lock
    self.assertRaises((ValueError, threading.ThreadError), lock.release)
  File "/usr/lib64/python2.7/unittest/case.py", line 513, in assertRaises
    callableObj(_args, *_kwargs)
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 989, in release
    return self._callmethod('release')
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 774, in _callmethod
    raise convert_to_error(kind, result)
RuntimeError: release unlocked lock

Check if we can raise the original threading.Error, or maybe monkeypatch it.

**Comment by nirs** [comment]
In Python 2, thread.error / threading.ThreadError inherit from Exception, and created in the thread extension module. This error is raised only from the thread module.

To be compatible with Python 2 and satisfy multiprocessing tests, cthreading must import thread.error from the thread module and raise it in Lock_release instead of RuntimeError.

This will break current monkeypatching code, checking that thread was not imported yet. Removing the check for thread module will make the the monkeypatching less safe; you would be able to import thread and use thread.allocate_lock before it is patched by cthreading.

Check if it is possible to import thread.error and unload the module, or remove it from sys.modules.

**Comment by nirs** [comment]
Fixed in https://github.com/nirs/cthreading/tree/thread-error.

**Comment by nirs** [comment]
Fixed in 5f13404c0531274e58dadd0303448b8d493cb2b1
